set_property CFGBVS VCCO [current_design]

set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports osc_100MHz_i]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports osc_100MHz_i]

#set_property CONFIG_MODE SPIx4 [current_design]
#set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

# SmartWave constraints
#set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {in[0]}]
#set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {in[1]}]
#set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {in[2]}]
#set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports {in[3]}]
#set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports {in[4]}]
#set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS33} [get_ports {in[5]}]
#set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {in[6]}]
#set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {in[7]}]
#set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {in[8]}]
#set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {in[9]}]
#set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {in[10]}]
#set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {in[11]}]
#set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {in[12]}]
#set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {in[13]}]
#set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports {in[14]}]
#set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {in[15]}]

#set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {out[0]}]
#set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS33} [get_ports {out[1]}]
#set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {out[2]}]
#set_property -dict {PACKAGE_PIN R7 IOSTANDARD LVCMOS33} [get_ports {out[3]}]
#set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {out[4]}]
#set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {out[5]}]
#set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {out[6]}]
#set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {out[7]}]
#set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {out[8]}]
#set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {out[9]}]
#set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {out[10]}]
#set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {out[11]}]
#set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {out[12]}]
#set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {out[13]}]
#set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {out[14]}]
#set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {out[15]}]

#set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[0]}]
#set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[1]}]
#set_property -dict {PACKAGE_PIN B5 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[2]}]
#set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[3]}]
#set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[4]}]
#set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[5]}]
#set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[6]}]
#set_property -dict {PACKAGE_PIN A7 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[7]}]
#set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[8]}]
#set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[9]}]
#set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[10]}]
#set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[11]}]
#set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[12]}]
#set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[13]}]
#set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[14]}]
#set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports {out_enable_n[15]}]

#set_property -dict {PACKAGE_PIN M5 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[0]}]
#set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[1]}]
#set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[2]}]
#set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[3]}]
#set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[4]}]
#set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[5]}]
#set_property -dict {PACKAGE_PIN G5 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[6]}]
#set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[7]}]
#set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[8]}]
#set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[9]}]
#set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[10]}]
#set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[11]}]
#set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[12]}]
#set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[13]}]
#set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[14]}]
#set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {pullup_enable_n[15]}]

#set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {pullup_level[0]}]
#set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports {pullup_level[1]}]
#set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {pullup_level[2]}]
#set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS33} [get_ports {pullup_level[3]}]
#set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports {pullup_level[4]}]
#set_property -dict {PACKAGE_PIN K5 IOSTANDARD LVCMOS33} [get_ports {pullup_level[5]}]
#set_property -dict {PACKAGE_PIN T7 IOSTANDARD LVCMOS33} [get_ports {pullup_level[6]}]
#set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVCMOS33} [get_ports {pullup_level[7]}]
#set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {pullup_level[8]}]
#set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {pullup_level[9]}]
#set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports {pullup_level[10]}]
#set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {pullup_level[11]}]
#set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {pullup_level[12]}]
#set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports {pullup_level[13]}]
#set_property -dict {PACKAGE_PIN L2 IOSTANDARD LVCMOS33} [get_ports {pullup_level[14]}]
#set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {pullup_level[15]}]



#set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports vcc_io_pg]

#set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports spi_cmd_cs_n]
#set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS33} [get_ports spi_cmd_clk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets spi_cmd_clk]
#set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports spi_cmd_mosi]
#set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports spi_cmd_miso]

#set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports reset_n_ext_i]



#set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports tp101]
#set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports tp102]
#set_property -dict {PACKAGE_PIN P8 IOSTANDARD LVCMOS33} [get_ports tp103]


## Quad SPI Flash
##set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS33} [get_ports qspi_cs] 
##set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports qspi_mosi] 
##set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports qspi_miso] 
##set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports qspi_do2]
##set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports qspi_do3]

set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports flash_clk]
set_property -dict {PACKAGE_PIN L12 IOSTANDARD LVCMOS33} [get_ports flash_csn]
# set_property IOSTANDARD LVCMOS33 [get_ports flash_holdn]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports flash_miso]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports flash_mosi]
# set_property IOSTANDARD LVCMOS33 [get_ports flash_wpn]

# set_property IOSTANDARD LVCMOS33 [get_ports ftdi_txd]
# set_property IOSTANDARD LVCMOS33 [get_ports ftdi_rxd]

# SmartWave constraints
#set_property OFFCHIP_TERM NONE [get_ports spi_cmd_miso]
#set_property OFFCHIP_TERM NONE [get_ports tp101]
#set_property OFFCHIP_TERM NONE [get_ports tp102]
#set_property OFFCHIP_TERM NONE [get_ports tp103]

set_property MARK_DEBUG true [get_nets cv32e40x_soc_inst/spi_flash_done]
set_property MARK_DEBUG true [get_nets cv32e40x_soc_inst/spi_flash_initialized]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list cv32e40x_soc_inst/spi_flash_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list cv32e40x_soc_inst/spi_flash_initialized]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
